// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: time_card_entry.
// - Entity ID: 102019c00c08af97ae2b0cc9a208fb481b7.
// - Entity Version: 102019c1cfd419d792289435971f2cb54b3.
// - Task ID: 698040b956ef0bb86b149560.
// - Task Root ID: 6979037d768a7cf710e2a1b8.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for TimeCardEntryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TimeCardEntryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  clock_in_timestamp: string;
  clock_out_timestamp?: string | null;
  location?: string | null;
  work_description?: string | null;
  notes?: string | null;
  lunch_start_timestamp?: string | null;
  lunch_end_timestamp?: string | null;
  lunch_duration_minutes?: number | null;
  total_hours?: number | null;
}

/**
 * ORM class for TimeCardEntry entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TimeCardEntryORM {
  private static instance: TimeCardEntryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c00c08af97ae2b0cc9a208fb481b7';
    this.entityName = 'time_card_entry';
    this.entityVersion = '102019c1cfd419d792289435971f2cb54b3';
    this.taskId = '698040b956ef0bb86b149560';
    this.taskRootId = '6979037d768a7cf710e2a1b8';
  }

  /**
   * Get singleton instance of TimeCardEntryORM
   */
  public static getInstance(): TimeCardEntryORM {
    if (!TimeCardEntryORM.instance) {
      TimeCardEntryORM.instance = new TimeCardEntryORM();
    }
    
    return TimeCardEntryORM.instance;
  }

  /**
   * Get time_card_entry by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getTimeCardEntryByIDs(ids: string[]): Promise<TimeCardEntryModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteTimeCardEntryByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all TimeCardEntry records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTimeCardEntry(): Promise<TimeCardEntryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TimeCardEntry record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTimeCardEntry(data: TimeCardEntryModel[]): Promise<TimeCardEntryModel[]> {
    const structured = data.map((item) => CreateData(TimeCardEntryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TimeCardEntry records
   */
  async purgeAllTimeCardEntry(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TimeCardEntry records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTimeCardEntry(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TimeCardEntryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get time_card_entry by Id index
   * This function gets data by index.
   */
  async getTimeCardEntryById(
    id: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryById(
    id: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexId(
      id
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by Id index
   */
  async deleteTimeCardEntryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by UserId index
   * This function gets data by index.
   */
  async getTimeCardEntryByUserId(
    user_id: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByUserId(
    user_id: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by UserId index
   */
  async deleteTimeCardEntryByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by ClockInTimestamp index
   * This function gets data by index.
   */
  async getTimeCardEntryByClockInTimestamp(
    clock_in_timestamp: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexClockInTimestamp(
      clock_in_timestamp
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by ClockInTimestamp index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByClockInTimestamp(
    clock_in_timestamp: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexClockInTimestamp(
      clock_in_timestamp
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by ClockInTimestamp index
   */
  async deleteTimeCardEntryByClockInTimestamp(
    clock_in_timestamp: string
  ): Promise<void> {
    const index = createIndexClockInTimestamp(
      clock_in_timestamp
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by ClockInTimestampUserId index
   * This function gets data by index.
   */
  async getTimeCardEntryByClockInTimestampUserId(
    clock_in_timestamp: string,
    user_id: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexClockInTimestampUserId(
      clock_in_timestamp,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by ClockInTimestampUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByClockInTimestampUserId(
    clock_in_timestamp: string,
    user_id: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexClockInTimestampUserId(
      clock_in_timestamp,
      user_id
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by ClockInTimestampUserId index
   */
  async deleteTimeCardEntryByClockInTimestampUserId(
    clock_in_timestamp: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexClockInTimestampUserId(
      clock_in_timestamp,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by ClockOutTimestamp index
   * This function gets data by index.
   */
  async getTimeCardEntryByClockOutTimestamp(
    clock_out_timestamp: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexClockOutTimestamp(
      clock_out_timestamp
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by ClockOutTimestamp index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByClockOutTimestamp(
    clock_out_timestamp: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexClockOutTimestamp(
      clock_out_timestamp
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by ClockOutTimestamp index
   */
  async deleteTimeCardEntryByClockOutTimestamp(
    clock_out_timestamp: string
  ): Promise<void> {
    const index = createIndexClockOutTimestamp(
      clock_out_timestamp
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by Location index
   * This function gets data by index.
   */
  async getTimeCardEntryByLocation(
    location: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexLocation(
      location
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by Location index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByLocation(
    location: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexLocation(
      location
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by Location index
   */
  async deleteTimeCardEntryByLocation(
    location: string
  ): Promise<void> {
    const index = createIndexLocation(
      location
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by DataCreator index
   * This function gets data by index.
   */
  async getTimeCardEntryByDataCreator(
    data_creator: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByDataCreator(
    data_creator: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by DataCreator index
   */
  async deleteTimeCardEntryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get time_card_entry by DataUpdater index
   * This function gets data by index.
   */
  async getTimeCardEntryByDataUpdater(
    data_updater: string,
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) time_card_entry by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTimeCardEntryByDataUpdater(
    data_updater: string,
    data: TimeCardEntryModel
  ): Promise<TimeCardEntryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TimeCardEntryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete time_card_entry by DataUpdater index
   */
  async deleteTimeCardEntryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TimeCardEntryModel data array
   */
  private resultToData(values: Data[]): TimeCardEntryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TimeCardEntryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TimeCardEntryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TimeCardEntryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TimeCardEntryModel => item !== null);
  }
}

/**
 * Convert TimeCardEntryModel data to Value array
 */
function TimeCardEntryModelToValues(data: TimeCardEntryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'clock_in_timestamp', type: DataType.string, defaultValue: '' },
    { key: 'clock_out_timestamp', type: DataType.string, defaultValue: null },
    { key: 'location', type: DataType.string, defaultValue: null },
    { key: 'work_description', type: DataType.string, defaultValue: null },
    { key: 'notes', type: DataType.string, defaultValue: null },
    { key: 'lunch_start_timestamp', type: DataType.string, defaultValue: null },
    { key: 'lunch_end_timestamp', type: DataType.string, defaultValue: null },
    { key: 'lunch_duration_minutes', type: DataType.number, defaultValue: null },
    { key: 'total_hours', type: DataType.number, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TimeCardEntryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TimeCardEntryModel data
 */
function TimeCardEntryModelFromValues(values: Value[]): TimeCardEntryModel {
  const data: Partial<TimeCardEntryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'clock_in_timestamp':
        data.clock_in_timestamp = ParseValue(value, DataType.string) as string;
        break;
      case 'clock_out_timestamp':
        data.clock_out_timestamp = ParseValue(value, DataType.string) as string | null;
        break;
      case 'location':
        data.location = ParseValue(value, DataType.string) as string | null;
        break;
      case 'work_description':
        data.work_description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'notes':
        data.notes = ParseValue(value, DataType.string) as string | null;
        break;
      case 'lunch_start_timestamp':
        data.lunch_start_timestamp = ParseValue(value, DataType.string) as string | null;
        break;
      case 'lunch_end_timestamp':
        data.lunch_end_timestamp = ParseValue(value, DataType.string) as string | null;
        break;
      case 'lunch_duration_minutes':
        data.lunch_duration_minutes = ParseValue(value, DataType.number) as number | null;
        break;
      case 'total_hours':
        data.total_hours = ParseValue(value, DataType.number) as number | null;
        break;
    }
  }
  
  return data as TimeCardEntryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for ClockInTimestamp fields
 */
function createIndexClockInTimestamp(
  clock_in_timestamp: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, clock_in_timestamp, 'clock_in_timestamp'),
  ];

  return {
    fields: ['clock_in_timestamp'],
    values
  };
}
/**
 * Create index for ClockInTimestampUserId fields
 */
function createIndexClockInTimestampUserId(
  clock_in_timestamp: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, clock_in_timestamp, 'clock_in_timestamp'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['clock_in_timestamp', 'user_id'],
    values
  };
}
/**
 * Create index for ClockOutTimestamp fields
 */
function createIndexClockOutTimestamp(
  clock_out_timestamp: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, clock_out_timestamp, 'clock_out_timestamp'),
  ];

  return {
    fields: ['clock_out_timestamp'],
    values
  };
}
/**
 * Create index for Location fields
 */
function createIndexLocation(
  location: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, location, 'location'),
  ];

  return {
    fields: ['location'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TimeCardEntryORM;