// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: sick_day.
// - Entity ID: 102019c0ae9a2467b359df325d86b6625af.
// - Entity Version: 102019c1cfd419d792289435971f2cb54b3.
// - Task ID: 698040b956ef0bb86b149560.
// - Task Root ID: 6979037d768a7cf710e2a1b8.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for SickDayModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SickDayModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  sick_date: string;
  hours: number;
  notes?: string | null;
}

/**
 * ORM class for SickDay entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SickDayORM {
  private static instance: SickDayORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c0ae9a2467b359df325d86b6625af';
    this.entityName = 'sick_day';
    this.entityVersion = '102019c1cfd419d792289435971f2cb54b3';
    this.taskId = '698040b956ef0bb86b149560';
    this.taskRootId = '6979037d768a7cf710e2a1b8';
  }

  /**
   * Get singleton instance of SickDayORM
   */
  public static getInstance(): SickDayORM {
    if (!SickDayORM.instance) {
      SickDayORM.instance = new SickDayORM();
    }
    
    return SickDayORM.instance;
  }

  /**
   * Get sick_day by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getSickDayByIDs(ids: string[]): Promise<SickDayModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteSickDayByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all SickDay records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSickDay(): Promise<SickDayModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SickDay record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSickDay(data: SickDayModel[]): Promise<SickDayModel[]> {
    const structured = data.map((item) => CreateData(SickDayModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SickDay records
   */
  async purgeAllSickDay(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SickDay records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSickDay(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SickDayModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get sick_day by Id index
   * This function gets data by index.
   */
  async getSickDayById(
    id: string,
  ): Promise<SickDayModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sick_day by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSickDayById(
    id: string,
    data: SickDayModel
  ): Promise<SickDayModel[]> {
    const index = createIndexId(
      id
    );

    const values = SickDayModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by Id index
   */
  async deleteSickDayById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sick_day by UserId index
   * This function gets data by index.
   */
  async getSickDayByUserId(
    user_id: string,
  ): Promise<SickDayModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sick_day by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSickDayByUserId(
    user_id: string,
    data: SickDayModel
  ): Promise<SickDayModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = SickDayModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by UserId index
   */
  async deleteSickDayByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sick_day by SickDate index
   * This function gets data by index.
   */
  async getSickDayBySickDate(
    sick_date: string,
  ): Promise<SickDayModel[]> {
    const index = createIndexSickDate(
      sick_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sick_day by SickDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSickDayBySickDate(
    sick_date: string,
    data: SickDayModel
  ): Promise<SickDayModel[]> {
    const index = createIndexSickDate(
      sick_date
    );

    const values = SickDayModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by SickDate index
   */
  async deleteSickDayBySickDate(
    sick_date: string
  ): Promise<void> {
    const index = createIndexSickDate(
      sick_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sick_day by SickDateUserId index
   * This function gets data by index.
   */
  async getSickDayBySickDateUserId(
    sick_date: string,
    user_id: string,
  ): Promise<SickDayModel[]> {
    const index = createIndexSickDateUserId(
      sick_date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sick_day by SickDateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSickDayBySickDateUserId(
    sick_date: string,
    user_id: string,
    data: SickDayModel
  ): Promise<SickDayModel[]> {
    const index = createIndexSickDateUserId(
      sick_date,
      user_id
    );

    const values = SickDayModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by SickDateUserId index
   */
  async deleteSickDayBySickDateUserId(
    sick_date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexSickDateUserId(
      sick_date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sick_day by DataCreator index
   * This function gets data by index.
   */
  async getSickDayByDataCreator(
    data_creator: string,
  ): Promise<SickDayModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sick_day by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSickDayByDataCreator(
    data_creator: string,
    data: SickDayModel
  ): Promise<SickDayModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SickDayModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by DataCreator index
   */
  async deleteSickDayByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sick_day by DataUpdater index
   * This function gets data by index.
   */
  async getSickDayByDataUpdater(
    data_updater: string,
  ): Promise<SickDayModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sick_day by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSickDayByDataUpdater(
    data_updater: string,
    data: SickDayModel
  ): Promise<SickDayModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SickDayModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sick_day by DataUpdater index
   */
  async deleteSickDayByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SickDayModel data array
   */
  private resultToData(values: Data[]): SickDayModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SickDayModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SickDayModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SickDayModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SickDayModel => item !== null);
  }
}

/**
 * Convert SickDayModel data to Value array
 */
function SickDayModelToValues(data: SickDayModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'sick_date', type: DataType.string, defaultValue: '' },
    { key: 'hours', type: DataType.number, defaultValue: 0 },
    { key: 'notes', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SickDayModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SickDayModel data
 */
function SickDayModelFromValues(values: Value[]): SickDayModel {
  const data: Partial<SickDayModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'sick_date':
        data.sick_date = ParseValue(value, DataType.string) as string;
        break;
      case 'hours':
        data.hours = ParseValue(value, DataType.number) as number;
        break;
      case 'notes':
        data.notes = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as SickDayModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for SickDate fields
 */
function createIndexSickDate(
  sick_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, sick_date, 'sick_date'),
  ];

  return {
    fields: ['sick_date'],
    values
  };
}
/**
 * Create index for SickDateUserId fields
 */
function createIndexSickDateUserId(
  sick_date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, sick_date, 'sick_date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['sick_date', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SickDayORM;